import { INodeProperties } from 'n8n-workflow';
export const getApiV1EmploymentsInfoGetAllFields: INodeProperties[] = [
	{
		displayName: 'Company ID',
		name: 'company_id',
		type: 'number',
		default: '',
		placeholder: '',
		description: 'Enter Company ID',
		required: true,
		displayOptions: {
			show: {
				operation: ['getApiV1EmploymentsInfo'],
				resource: ['employments'],
			},
		},
	},
	{
		displayName: 'Filters[start Date]',
		name: 'filtersSTARTstart_dateEND',
		type: 'string',
		default: '',
		placeholder: '',
		description: 'Start date in ISO 8601 format with time and UTC offset',
		required: true,
		displayOptions: {
			show: {
				operation: ['getApiV1EmploymentsInfo'],
				resource: ['employments'],
			},
		},
	},
	{
		displayName: 'Filters[end Date]',
		name: 'filtersSTARTend_dateEND',
		type: 'string',
		default: '',
		placeholder: '',
		description: 'End date in ISO 8601 format with time and UTC offset',
		required: true,
		displayOptions: {
			show: {
				operation: ['getApiV1EmploymentsInfo'],
				resource: ['employments'],
			},
		},
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				operation: ['getApiV1EmploymentsInfo'],
				resource: ['employments'],
			},
		},
		options: [
			{
				displayName: 'Page',
				name: 'page',
				type: 'number',
				default: '',
				placeholder: '',
				description: 'Page no',
			},
			{
				displayName: 'Per Page',
				name: 'per_page',
				type: 'number',
				default: '',
				placeholder: '',
				description: 'Total employees page page',
			},
			{
				displayName: 'Filters[employment IDs][]',
				name: 'filtersSTARTemployment_idsENDSTARTEND',
				type: 'json',
				typeOptions: {
					multipleValues: true,
					multipleValueButtonText: 'Add Tag',
				},
				default: '',
				placeholder: '',
				description: 'Employment IDs',
			},
			{
				displayName: 'Filters[location IDs][]',
				name: 'filtersSTARTlocation_idsENDSTARTEND',
				type: 'json',
				typeOptions: {
					multipleValues: true,
					multipleValueButtonText: 'Add Tag',
				},
				default: '',
				placeholder: '',
				description: 'Location IDs',
			},
			{
				displayName: 'Filters[locations Position_IDs][]',
				name: 'filtersSTARTlocations_position_idsENDSTARTEND',
				type: 'json',
				typeOptions: {
					multipleValues: true,
					multipleValueButtonText: 'Add Tag',
				},
				default: '',
				placeholder: '',
				description: 'Locations position IDs',
			},
			{
				displayName: 'Filters[shift Rotation_group_IDs][]',
				name: 'filtersSTARTshift_rotation_group_idsENDSTARTEND',
				type: 'json',
				typeOptions: {
					multipleValues: true,
					multipleValueButtonText: 'Add Tag',
				},
				default: '',
				placeholder: '',
				description: 'Shift rotation group IDs',
			},
			{
				displayName: 'Filters[search String]',
				name: 'filtersSTARTsearch_stringEND',
				type: 'string',
				default: '',
				placeholder: '',
				description: 'Search employee by the name or staff number',
			},
			{
				displayName: 'Filters[tag IDs][]',
				name: 'filtersSTARTtag_idsENDSTARTEND',
				type: 'json',
				typeOptions: {
					multipleValues: true,
					multipleValueButtonText: 'Add Tag',
				},
				default: '',
				placeholder: '',
				description: 'Filter by an array of Employee Attribute IDs',
			},
			{
				displayName: 'Sort Name',
				name: 'sort_name',
				type: 'string',
				default: '',
				placeholder: '',
				description: 'Sorting param',
			},
			{
				displayName: 'Sort Direction',
				name: 'sort_direction',
				type: 'string',
				default: '',
				placeholder: '',
				description: 'Sorting direction',
			},
		],
	},
];
