import { INodeProperties } from 'n8n-workflow';
export const getApiV1AbsencesGetAllFields: INodeProperties[] = [
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				operation: ['getApiV1Absences'],
				resource: ['absences'],
			},
		},
		options: [
			{
				displayName: 'Company ID',
				name: 'company_id',
				type: 'number',
				default: '',
				placeholder: '',
				description: 'Single Company ID',
			},
			{
				displayName: 'Page',
				name: 'page',
				type: 'number',
				default: '',
				placeholder: '',
				description: 'Pages starts with 1',
			},
			{
				displayName: 'Per Page',
				name: 'per_page',
				type: 'number',
				default: '',
				placeholder: '',
				description: 'Between 1 and 1000',
			},
			{
				displayName: 'Updated After',
				name: 'updated_after',
				type: 'string',
				default: '',
				placeholder: '',
				description: 'Return all records which are updated after',
			},
			{
				displayName: 'Created After',
				name: 'created_after',
				type: 'string',
				default: '',
				placeholder: '',
				description: 'Return all records which are created after',
			},
			{
				displayName: 'Updated Before',
				name: 'updated_before',
				type: 'string',
				default: '',
				placeholder: '',
				description: 'Return all records which are updated before',
			},
			{
				displayName: 'Created Before',
				name: 'created_before',
				type: 'string',
				default: '',
				placeholder: '',
				description: 'Return all records which are created before',
			},
			{
				displayName: 'ID',
				name: 'id',
				type: 'number',
				default: '',
				placeholder: '',
				description: 'Single Absence ID',
			},
			{
				displayName: 'IDs[]',
				name: 'idsSTARTEND',
				type: 'json',
				typeOptions: {
					multipleValues: true,
					multipleValueButtonText: 'Add Tag',
				},
				default: '',
				placeholder: '',
				description: 'Array of Absence ID',
			},
			{
				displayName: 'Company IDs[]',
				name: 'company_idsSTARTEND',
				type: 'json',
				typeOptions: {
					multipleValues: true,
					multipleValueButtonText: 'Add Tag',
				},
				default: '',
				placeholder: '',
				description: 'Array of Company ID',
			},
			{
				displayName: 'Absence Reason_ID',
				name: 'absence_reason_id',
				type: 'number',
				default: '',
				placeholder: '',
				description: 'Single Absence Reason ID',
			},
			{
				displayName: 'Absence Reason_IDs[]',
				name: 'absence_reason_idsSTARTEND',
				type: 'json',
				typeOptions: {
					multipleValues: true,
					multipleValueButtonText: 'Add Tag',
				},
				default: '',
				placeholder: '',
				description: 'Array of Absence Reason ID',
			},
			{
				displayName: 'Employment ID',
				name: 'employment_id',
				type: 'number',
				default: '',
				placeholder: '',
				description: 'Single Employment ID',
			},
			{
				displayName: 'Employment IDs[]',
				name: 'employment_idsSTARTEND',
				type: 'json',
				typeOptions: {
					multipleValues: true,
					multipleValueButtonText: 'Add Tag',
				},
				default: '',
				placeholder: '',
				description: 'Array of Employment ID',
			},
			{
				displayName: 'Emp Staff_number',
				name: 'emp_staff_number',
				type: 'number',
				default: '',
				placeholder: '',
				description: 'Single Employment staff number',
			},
			{
				displayName: 'Emp Staff_numbers[]',
				name: 'emp_staff_numbersSTARTEND',
				type: 'json',
				typeOptions: {
					multipleValues: true,
					multipleValueButtonText: 'Add Tag',
				},
				default: '',
				placeholder: '',
				description: 'Array of Employment staff number',
			},
			{
				displayName: 'Emp Status',
				name: 'emp_status',
				type: 'string',
				default: '',
				placeholder: '',
				description: 'Single employment status',
			},
			{
				displayName: 'Emp Statuses[]',
				name: 'emp_statusesSTARTEND',
				type: 'json',
				typeOptions: {
					multipleValues: true,
					multipleValueButtonText: 'Add Tag',
				},
				default: '',
				placeholder: '',
				description: 'Array of employment statuses',
			},
			{
				displayName: 'Location ID',
				name: 'location_id',
				type: 'number',
				default: '',
				placeholder: '',
				description: 'Single Location ID',
			},
			{
				displayName: 'Location IDs[]',
				name: 'location_idsSTARTEND',
				type: 'json',
				typeOptions: {
					multipleValues: true,
					multipleValueButtonText: 'Add Tag',
				},
				default: '',
				placeholder: '',
				description: 'Array of Location ID',
			},
			{
				displayName: 'State',
				name: 'state',
				type: 'string',
				default: '',
				placeholder: '',
				description: 'State of absence',
			},
			{
				displayName: 'States[]',
				name: 'statesSTARTEND',
				type: 'json',
				typeOptions: {
					multipleValues: true,
					multipleValueButtonText: 'Add Tag',
				},
				default: '',
				placeholder: '',
				description: 'Array of states of absences',
			},
			{
				displayName: 'PaID',
				name: 'paid',
				type: 'boolean',
				default: false,
				placeholder: '',
				description: 'Whether Paid or unpaid Absences',
			},
			{
				displayName: 'Attachment',
				name: 'attachment',
				type: 'boolean',
				default: false,
				placeholder: '',
				description:
					"Whether Attached file'true' returns only those absences which have attachment;'false' returns only those absences which do not have attachment; 'empty value' returns all absences regardless of attachments",
			},
			{
				displayName: 'Starts At',
				name: 'starts_at',
				type: 'string',
				default: '',
				placeholder: '',
				description: 'Start of absence',
			},
			{
				displayName: 'Ends At',
				name: 'ends_at',
				type: 'string',
				default: '',
				placeholder: '',
				description: 'End of absence',
			},
			{
				displayName: 'Order Key',
				name: 'order_key',
				type: 'string',
				default: '',
				placeholder: '',
				description: 'Sort Absences',
			},
			{
				displayName: 'Order Dir',
				name: 'order_dir',
				type: 'string',
				default: '',
				placeholder: '',
				description: 'Sort Absences',
			},
			{
				displayName: 'Include Deleted_staff_shifts_info',
				name: 'include_deleted_staff_shifts_info',
				type: 'boolean',
				default: false,
				placeholder: '',
				description: 'Whether Include deleted staff shifts information',
			},
			{
				displayName: 'Extended Info',
				name: 'extended_info',
				type: 'boolean',
				default: false,
				placeholder: '',
				description: 'Whether Paid or unpaid Absences',
			},
		],
	},
];
