import { INodeProperties } from 'n8n-workflow';
export const getApiV1EmploymentsPositionsGetAllFields: INodeProperties[] = [
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				operation: ['getApiV1EmploymentsPositions'],
				resource: ['employments_positions'],
			},
		},
		options: [
			{
				displayName: 'Company ID',
				name: 'company_id',
				type: 'number',
				default: '',
				placeholder: '',
				description: 'Filter for single Comapny ID',
			},
			{
				displayName: 'Page',
				name: 'page',
				type: 'number',
				default: 1,
				placeholder: '',
				description: 'Pages starts with 1',
			},
			{
				displayName: 'Per Page',
				name: 'per_page',
				type: 'number',
				default: 1000,
				placeholder: '',
				description: 'Between 1 and 1000',
			},
			{
				displayName: 'Updated After',
				name: 'updated_after',
				type: 'string',
				default: '',
				placeholder: '',
				description: 'Return all records which are updated after',
			},
			{
				displayName: 'Created After',
				name: 'created_after',
				type: 'string',
				default: '',
				placeholder: '',
				description: 'Return all records which are created after',
			},
			{
				displayName: 'Updated Before',
				name: 'updated_before',
				type: 'string',
				default: '',
				placeholder: '',
				description: 'Return all records which are updated before',
			},
			{
				displayName: 'Created Before',
				name: 'created_before',
				type: 'string',
				default: '',
				placeholder: '',
				description: 'Return all records which are created before',
			},
			{
				displayName: 'ID',
				name: 'id',
				type: 'number',
				default: '',
				placeholder: '',
				description: 'Filter for single EmploymentsPosition ID',
			},
			{
				displayName: 'IDs[]',
				name: 'ids[]',
				type: 'string',
				default: '',
				placeholder: '',
				description: 'Filter an array of EmploymentsPosition ID',
			},
			{
				displayName: 'Employment ID',
				name: 'employment_id',
				type: 'number',
				default: '',
				placeholder: '',
				description: 'Filter for single Employment ID',
			},
			{
				displayName: 'Employment IDs[]',
				name: 'employment_ids[]',
				type: 'string',
				default: '',
				placeholder: '',
				description: 'Filter an array of Employment ID',
			},
			{
				displayName: 'Location ID',
				name: 'location_id',
				type: 'number',
				default: '',
				placeholder: '',
				description: 'Filter for single Location ID',
			},
			{
				displayName: 'Locations Position_ID',
				name: 'locations_position_id',
				type: 'number',
				default: '',
				placeholder: '',
				description: 'Filter for single LocationsPosition ID',
			},
			{
				displayName: 'Locations Position_IDs[]',
				name: 'locations_position_ids[]',
				type: 'string',
				default: '',
				placeholder: '',
				description: 'Filter an array of LocationsPosition ID',
			},
			{
				displayName: 'Company IDs[]',
				name: 'company_ids[]',
				type: 'string',
				default: '',
				placeholder: '',
				description: 'Filter an array of Company ID',
			},
			{
				displayName: 'Response Format',
				name: 'response_format',
				type: 'string',
				default: '',
				placeholder: '',
				description: 'Set to nested if result should look like {items: [..], total: x}',
			},
		],
	},
];
