import { INodeProperties } from 'n8n-workflow';
export const getApiV1ShiftsIdAvailableEmploymentsGetAllFields: INodeProperties[] = [
	{
		displayName: 'ID',
		name: 'id',
		type: 'number',
		default: '',
		placeholder: '',
		description: 'Enter Shift ID',
		required: true,
		displayOptions: {
			show: {
				operation: ['getApiV1ShiftsIdAvailableEmployments'],
				resource: ['shifts'],
			},
		},
	},
	{
		displayName: 'Company ID',
		name: 'company_id',
		type: 'number',
		default: '',
		placeholder: '',
		description: 'Enter Company ID',
		required: true,
		displayOptions: {
			show: {
				operation: ['getApiV1ShiftsIdAvailableEmployments'],
				resource: ['shifts'],
			},
		},
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				operation: ['getApiV1ShiftsIdAvailableEmployments'],
				resource: ['shifts'],
			},
		},
		options: [
			{
				displayName: 'Page',
				name: 'page',
				type: 'number',
				default: '',
				placeholder: '',
				description: 'Enter Page (Page size is always 10)',
			},
			{
				displayName: 'Per Page',
				name: 'per_page',
				type: 'number',
				default: '',
				placeholder: '',
				description: 'Enter Amount of data to return on each request',
			},
			{
				displayName: 'Search String',
				name: 'search_string',
				type: 'string',
				default: '',
				placeholder: '',
				description: 'Enter Search employees by name',
			},
			{
				displayName: 'Filters[without Shift_conflicts]',
				name: 'filtersSTARTwithout_shift_conflictsEND',
				type: 'boolean',
				default: false,
				placeholder: '',
				description: 'Whether Show only employees without other shifts at this time',
			},
			{
				displayName: 'Filters[without Absence_conflicts]',
				name: 'filtersSTARTwithout_absence_conflictsEND',
				type: 'boolean',
				default: false,
				placeholder: '',
				description: 'Whether Show only employees without absences at this time',
			},
			{
				displayName: 'Filters[with Join_requests]',
				name: 'filtersSTARTwith_join_requestsEND',
				type: 'boolean',
				default: false,
				placeholder: '',
				description: 'Whether Show only employees with join requests for this shift',
			},
			{
				displayName: 'Filters[with Master_position]',
				name: 'filtersSTARTwith_master_positionEND',
				type: 'boolean',
				default: false,
				placeholder: '',
				description: 'Whether Show only employees with master position same as shift position',
			},
			{
				displayName: 'Filters[with These_qualification_IDs][]',
				name: 'filtersSTARTwith_these_qualification_idsENDSTARTEND',
				type: 'json',
				typeOptions: {
					multipleValues: true,
					multipleValueButtonText: 'Add Tag',
				},
				default: '',
				placeholder: '',
				description: 'Enter Show only employees with passed qualification IDs',
			},
			{
				displayName: 'Filters[availability Filters][available]',
				name: 'filtersSTARTavailability_filtersENDSTARTavailableEND',
				type: 'boolean',
				default: false,
				placeholder: '',
				description: 'Whether Show only employees who is fully available',
			},
			{
				displayName: 'Filters[availability Filters][partial_available]',
				name: 'filtersSTARTavailability_filtersENDSTARTpartial_availableEND',
				type: 'boolean',
				default: false,
				placeholder: '',
				description: 'Whether Show only employees who is partially available',
			},
			{
				displayName: 'Filters[availability Filters][partial_both]',
				name: 'filtersSTARTavailability_filtersENDSTARTpartial_bothEND',
				type: 'boolean',
				default: false,
				placeholder: '',
				description:
					'Whether Show only employees who is partially available and partially unavailable',
			},
			{
				displayName: 'Filters[availability Filters][partial_unavailable]',
				name: 'filtersSTARTavailability_filtersENDSTARTpartial_unavailableEND',
				type: 'boolean',
				default: false,
				placeholder: '',
				description: 'Whether Show only employees who is partially unavailable',
			},
			{
				displayName: 'Filters[availability Filters][unavailable]',
				name: 'filtersSTARTavailability_filtersENDSTARTunavailableEND',
				type: 'boolean',
				default: false,
				placeholder: '',
				description: 'Whether Show only employees who is fully unavailable',
			},
			{
				displayName: 'Filters[availability Filters][neutral]',
				name: 'filtersSTARTavailability_filtersENDSTARTneutralEND',
				type: 'boolean',
				default: false,
				placeholder: '',
				description: 'Whether Show only employees who has no information about availabilities',
			},
			{
				displayName: 'Filters[tag IDs][]',
				name: 'filtersSTARTtag_idsENDSTARTEND',
				type: 'json',
				typeOptions: {
					multipleValues: true,
					multipleValueButtonText: 'Add Tag',
				},
				default: '',
				placeholder: '',
				description: 'Enter Filter by an array of Employee Attribute IDs',
			},
			{
				displayName: 'Sort Name',
				name: 'sort_name',
				type: 'string',
				default: '',
				placeholder: '',
				description: 'Enter Sorting param',
			},
			{
				displayName: 'Sort Direction',
				name: 'sort_direction',
				type: 'string',
				default: '',
				placeholder: '',
				description: 'Enter Sorting direction',
			},
		],
	},
];
