import { INodeProperties } from 'n8n-workflow';
export const postApiV2EmploymentsCreateFields: INodeProperties[] = [
	{
		displayName: 'Company ID',
		name: 'company_id',
		type: 'number',
		required: true,
		default: '',
		displayOptions: {
			show: {
				operation: ['postApiV2Employments'],
				resource: ['employments'],
			},
		},
		placeholder: '',
		description: 'Enter company ID',
	},
	{
		displayName: 'First Name',
		name: 'first_name',
		type: 'string',
		required: true,
		default: '',
		displayOptions: {
			show: {
				operation: ['postApiV2Employments'],
				resource: ['employments'],
			},
		},
		placeholder: '',
		description: 'Enter first name',
	},
	{
		displayName: 'Last Name',
		name: 'last_name',
		type: 'string',
		required: true,
		default: '',
		displayOptions: {
			show: {
				operation: ['postApiV2Employments'],
				resource: ['employments'],
			},
		},
		placeholder: '',
		description: 'Enter last name',
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				operation: ['postApiV2Employments'],
				resource: ['employments'],
			},
		},
		options: [
			{
				displayName: 'Is PaID_monthly',
				name: 'is_paid_monthly',
				type: 'boolean',
				default: '',
				placeholder: '',
				description: '',
			},
			{
				displayName: 'Sso Only',
				name: 'sso_only',
				type: 'boolean',
				default: '',
				placeholder: '',
				description:
					'Create user as Single Sign-On only user Password will be ignored if this flag is set',
			},
			{
				displayName: 'User Token',
				name: 'user_token',
				type: 'number',
				default: '',
				placeholder: '',
				description: 'Token for punch-timing',
			},
			{
				displayName: 'Maximum Money_enabled',
				name: 'maximum_money_enabled',
				type: 'boolean',
				default: '',
				placeholder: '',
				description: '',
			},
			{
				displayName: 'Maximum Money',
				name: 'maximum_money',
				type: 'number',
				default: '',
				placeholder: '',
				description: '',
			},
			{
				displayName: 'Employment Work_hour_attributes[mon_minutes]',
				name: 'employment_work_hour_attributes[mon_minutes]',
				type: 'number',
				default: '',
				placeholder: '',
				description: '',
			},
			{
				displayName: 'Employment Work_hour_attributes[tue_minutes]',
				name: 'employment_work_hour_attributes[tue_minutes]',
				type: 'number',
				default: '',
				placeholder: '',
				description: '',
			},
			{
				displayName: 'Employment Work_hour_attributes[wed_minutes]',
				name: 'employment_work_hour_attributes[wed_minutes]',
				type: 'number',
				default: '',
				placeholder: '',
				description: '',
			},
			{
				displayName: 'Employment Work_hour_attributes[thu_minutes]',
				name: 'employment_work_hour_attributes[thu_minutes]',
				type: 'number',
				default: '',
				placeholder: '',
				description: '',
			},
			{
				displayName: 'Employment Work_hour_attributes[fri_minutes]',
				name: 'employment_work_hour_attributes[fri_minutes]',
				type: 'number',
				default: '',
				placeholder: '',
				description: '',
			},
			{
				displayName: 'Employment Work_hour_attributes[sat_minutes]',
				name: 'employment_work_hour_attributes[sat_minutes]',
				type: 'number',
				default: '',
				placeholder: '',
				description: '',
			},
			{
				displayName: 'Employment Work_hour_attributes[sun_minutes]',
				name: 'employment_work_hour_attributes[sun_minutes]',
				type: 'number',
				default: '',
				placeholder: '',
				description: '',
			},
			{
				displayName: 'Employment Work_hour_attributes[vacation_minutes]',
				name: 'employment_work_hour_attributes[vacation_minutes]',
				type: 'number',
				default: '',
				placeholder: '',
				description: '',
			},
			{
				displayName: 'Exit Date',
				name: 'exit_date',
				type: 'string',
				default: '',
				placeholder: '',
				description: '',
			},
			{
				displayName: 'Exit Month_payed_partially',
				name: 'exit_month_payed_partially',
				type: 'boolean',
				default: '',
				placeholder: '',
				description: '',
			},
			{
				displayName: 'Billing Type_ID',
				name: 'billing_type_id',
				type: 'number',
				default: '',
				placeholder: '',
				description: ' 1 = abrechnen (is billed);  2 = nicht abrechnen (is not billed)',
			},
			{
				displayName: 'note',
				name: 'note',
				type: 'string',
				default: '',
				placeholder: '',
				description: '',
			},
			{
				displayName: 'Phone Number',
				name: 'phone_number',
				type: 'string',
				default: '',
				placeholder: '',
				description: '',
			},
			{
				displayName: 'Staff Number',
				name: 'staff_number',
				type: 'string',
				default: '',
				placeholder: '',
				description: '',
			},
			{
				displayName: 'email',
				name: 'email',
				type: 'string',
				default: '',
				placeholder: '',
				description: 'email used to login to the employment created',
			},
			{
				displayName: 'password',
				name: 'password',
				type: 'string',
				default: '',
				placeholder: '',
				description: '',
			},
		],
	},
];
