import { INodeProperties } from 'n8n-workflow';
        export const getApiV1RequestsGetAllFields: INodeProperties[] = [
        {
            displayName: 'Additional Fields',
            name: 'additionalFields',
            type: 'collection',
            placeholder: 'Add Field',
            default: {},
            displayOptions: {
                show: {
                    operation: ['getApiV1Requests'],
                    resource: ['requests'],
                },
            },
            options: [{
                            displayName: 'Company ID', 
                            name: 'company_id',
                            type: 'number', 
                            default: '',
                            placeholder: '',
                            description: "Enter ", 
                        },
{
                            displayName: 'Page', 
                            name: 'page',
                            type: 'number', 
                            default: '',
                            placeholder: '',
                            description: "Enter Pages starts with 1", 
                        },
{
                            displayName: 'Per Page', 
                            name: 'per_page',
                            type: 'number', 
                            default: '',
                            placeholder: '',
                            description: "Enter Between 1 and 1000", 
                        },
{
                            displayName: 'Updated After', 
                            name: 'updated_after',
                            type: 'string', 
                            default: '',
                            placeholder: '',
                            description: "Enter Return all records which are updated after", 
                        },
{
                            displayName: 'Created After', 
                            name: 'created_after',
                            type: 'string', 
                            default: '',
                            placeholder: '',
                            description: "Enter Return all records which are created after", 
                        },
{
                            displayName: 'Updated Before', 
                            name: 'updated_before',
                            type: 'string', 
                            default: '',
                            placeholder: '',
                            description: "Enter Return all records which are updated before", 
                        },
{
                            displayName: 'Created Before', 
                            name: 'created_before',
                            type: 'string', 
                            default: '',
                            placeholder: '',
                            description: "Enter Return all records which are created before", 
                        },
{
                            displayName: 'ID', 
                            name: 'id',
                            type: 'number', 
                            default: '',
                            placeholder: '',
                            description: "Enter Filter for single Request ID", 
                        },
{
                            displayName: 'IDs[]', 
                            name: 'idsSTARTEND',
                            type: 'json', 
                            typeOptions: {
                                multipleValues: true,
                                multipleValueButtonText: 'Add Tag',
                            },
                            default: '',
                            placeholder: '',
                            description: "Enter Filter an array of Request ID", 
                        },
{
                            displayName: 'Shift ID', 
                            name: 'shift_id',
                            type: 'number', 
                            default: '',
                            placeholder: '',
                            description: "Enter Filter for single Shift ID", 
                        },
{
                            displayName: 'Shift IDs[]', 
                            name: 'shift_idsSTARTEND',
                            type: 'json', 
                            typeOptions: {
                                multipleValues: true,
                                multipleValueButtonText: 'Add Tag',
                            },
                            default: '',
                            placeholder: '',
                            description: "Enter Filter an array of Shift ID", 
                        },
{
                            displayName: 'Employment ID', 
                            name: 'employment_id',
                            type: 'number', 
                            default: '',
                            placeholder: '',
                            description: "Enter Filter for single Employment ID", 
                        },
{
                            displayName: 'Employment IDs[]', 
                            name: 'employment_idsSTARTEND',
                            type: 'json', 
                            typeOptions: {
                                multipleValues: true,
                                multipleValueButtonText: 'Add Tag',
                            },
                            default: '',
                            placeholder: '',
                            description: "Enter Filter an array of Employment ID", 
                        },
{
                            displayName: 'Shiftplan ID', 
                            name: 'shiftplan_id',
                            type: 'number', 
                            default: '',
                            placeholder: '',
                            description: "Enter Filter for single Shiftplan ID", 
                        },
{
                            displayName: 'Shiftplan IDs[]', 
                            name: 'shiftplan_idsSTARTEND',
                            type: 'json', 
                            typeOptions: {
                                multipleValues: true,
                                multipleValueButtonText: 'Add Tag',
                            },
                            default: '',
                            placeholder: '',
                            description: "Enter Filter an array of Shiftplan ID", 
                        },
{
                            displayName: 'Type', 
                            name: 'type',
                            type: 'string', 
                            default: '',
                            placeholder: '',
                            description: "Enter Filter for single Request type", 
                        },
{
                            displayName: 'Types[]', 
                            name: 'typesSTARTEND',
                            type: 'json', 
                            typeOptions: {
                                multipleValues: true,
                                multipleValueButtonText: 'Add Tag',
                            },
                            default: '',
                            placeholder: '',
                            description: "Enter Filter an array of Request type", 
                        },
{
                            displayName: 'Only Open', 
                            name: 'only_open',
                            type: 'boolean', 
                            default: false,
                            placeholder: '',
                            description: "Whether Filter for open shifts", 
                        },
	],
    },];