import { INodeProperties } from 'n8n-workflow';
export const getApiV1EvaluationsGetAllFields: INodeProperties[] = [
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				operation: ['getApiV1Evaluations'],
				resource: ['evaluations'],
			},
		},
		options: [
			{
				displayName: 'Company ID',
				name: 'company_id',
				type: 'number',
				default: '',
				placeholder: '',
				description: 'Enter Company ID',
			},
			{
				displayName: 'Page',
				name: 'page',
				type: 'number',
				default: '',
				placeholder: '',
				description: 'Pages starts with 1',
			},
			{
				displayName: 'Per Page',
				name: 'per_page',
				type: 'number',
				default: '',
				placeholder: '',
				description: 'Enter Per Page',
			},
			{
				displayName: 'Starts At',
				name: 'starts_at',
				type: 'string',
				default: '',
				placeholder: '',
				description: 'Enter Starts At',
			},
			{
				displayName: 'Ends At',
				name: 'ends_at',
				type: 'string',
				default: '',
				placeholder: '',
				description: 'Enter Ends At',
			},
			{
				displayName: 'IDs[]',
				name: 'idsSTARTEND',
				type: 'json',
				typeOptions: {
					multipleValues: true,
					multipleValueButtonText: 'Add Tag',
				},
				default: '',
				placeholder: '',
				description: 'Filter an array of Evaluation ID',
			},
			{
				displayName: 'State',
				name: 'state',
				type: 'string',
				default: '',
				placeholder: '',
				description: 'Enter State',
			},
			{
				displayName: 'Employment ID',
				name: 'employment_id',
				type: 'number',
				default: '',
				placeholder: '',
				description: 'Filter for single Employment ID',
			},
			{
				displayName: 'Employment IDs[]',
				name: 'employment_idsSTARTEND',
				type: 'json',
				typeOptions: {
					multipleValues: true,
					multipleValueButtonText: 'Add Tag',
				},
				default: '',
				placeholder: '',
				description: 'Filter an array of Employment ID',
			},
			{
				displayName: 'Shift ID',
				name: 'shift_id',
				type: 'number',
				default: '',
				placeholder: '',
				description: 'Filter for single Shift ID',
			},
			{
				displayName: 'Shift IDs[]',
				name: 'shift_idsSTARTEND',
				type: 'json',
				typeOptions: {
					multipleValues: true,
					multipleValueButtonText: 'Add Tag',
				},
				default: '',
				placeholder: '',
				description: 'Filter an array of Shift ID',
			},
			{
				displayName: 'Emp Status',
				name: 'emp_status',
				type: 'string',
				default: '',
				placeholder: '',
				description: 'Filter for a single employment status',
			},
			{
				displayName: 'Emp Statuses[]',
				name: 'emp_statusesSTARTEND',
				type: 'json',
				typeOptions: {
					multipleValues: true,
					multipleValueButtonText: 'Add Tag',
				},
				default: '',
				placeholder: '',
				description: 'Filter for an array of employment statuses',
			},
			{
				displayName: 'Location ID',
				name: 'location_id',
				type: 'number',
				default: '',
				placeholder: '',
				description: 'Filter for single Location ID',
			},
			{
				displayName: 'Location IDs[]',
				name: 'location_idsSTARTEND',
				type: 'json',
				typeOptions: {
					multipleValues: true,
					multipleValueButtonText: 'Add Tag',
				},
				default: '',
				placeholder: '',
				description: 'Filter an array of Location ID',
			},
			{
				displayName: 'Position ID',
				name: 'position_id',
				type: 'number',
				default: '',
				placeholder: '',
				description: 'Filter for single Position ID',
			},
			{
				displayName: 'Position IDs[]',
				name: 'position_idsSTARTEND',
				type: 'json',
				typeOptions: {
					multipleValues: true,
					multipleValueButtonText: 'Add Tag',
				},
				default: '',
				placeholder: '',
				description: 'Filter an array of Position ID',
			},
			{
				displayName: 'Position Status',
				name: 'position_status',
				type: 'string',
				default: '',
				placeholder: '',
				description: 'Filter for deleted/undeleted positions',
			},
			{
				displayName: 'Locations Position_ID',
				name: 'locations_position_id',
				type: 'number',
				default: '',
				placeholder: '',
				description: 'Filter for single LocationsPosition ID',
			},
			{
				displayName: 'Locations Position_IDs[]',
				name: 'locations_position_idsSTARTEND',
				type: 'json',
				typeOptions: {
					multipleValues: true,
					multipleValueButtonText: 'Add Tag',
				},
				default: '',
				placeholder: '',
				description: 'Filter an array of LocationsPosition ID',
			},
			{
				displayName: 'Include Payments',
				name: 'include_payments',
				type: 'boolean',
				default: false,
				placeholder: '',
				description: 'Whether Include Payments in response',
			},
			{
				displayName: 'Updated After',
				name: 'updated_after',
				type: 'string',
				default: '',
				placeholder: '',
				description: 'Return all records which are updated after',
			},
			{
				displayName: 'Created After',
				name: 'created_after',
				type: 'string',
				default: '',
				placeholder: '',
				description: 'Return all records which are created after',
			},
			{
				displayName: 'Updated Before',
				name: 'updated_before',
				type: 'string',
				default: '',
				placeholder: '',
				description: 'Return all records which are updated before',
			},
			{
				displayName: 'Created Before',
				name: 'created_before',
				type: 'string',
				default: '',
				placeholder: '',
				description: 'Return all records which are created before',
			},
		],
	},
];
