import { INodeProperties } from 'n8n-workflow';
export const postApiV1ShiftsCreateFields: INodeProperties[] = [
	{
		displayName: 'Starts At',
		name: 'starts_at',
		type: 'string',
		required: true,
		default: '',
		displayOptions: {
			show: {
				operation: ['postApiV1Shifts'],
				resource: ['shifts'],
			},
		},
		placeholder: '',
		description: 'Start of the shift',
	},
	{
		displayName: 'Ends At',
		name: 'ends_at',
		type: 'string',
		required: true,
		default: '',
		displayOptions: {
			show: {
				operation: ['postApiV1Shifts'],
				resource: ['shifts'],
			},
		},
		placeholder: '',
		description: 'End of the shift',
	},
	{
		displayName: 'Workers',
		name: 'workers',
		type: 'number',
		required: true,
		default: '',
		displayOptions: {
			show: {
				operation: ['postApiV1Shifts'],
				resource: ['shifts'],
			},
		},
		placeholder: '',
		description: 'Number of workers',
	},
	{
		displayName: 'Shiftplan ID',
		name: 'shiftplan_id',
		type: 'number',
		required: true,
		default: '',
		displayOptions: {
			show: {
				operation: ['postApiV1Shifts'],
				resource: ['shifts'],
			},
		},
		placeholder: '',
		description: 'ID of an Shiftplan',
	},
	{
		displayName: 'Locations Position_ID',
		name: 'locations_position_id',
		type: 'number',
		required: true,
		default: '',
		displayOptions: {
			show: {
				operation: ['postApiV1Shifts'],
				resource: ['shifts'],
			},
		},
		placeholder: '',
		description: 'ID of LocationsPosition - Location needs to match the location of the shiftplan',
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				operation: ['postApiV1Shifts'],
				resource: ['shifts'],
			},
		},
		options: [
			{
				displayName: 'Note',
				name: 'note',
				type: 'string',
				default: '',
				placeholder: '',
				description: 'Note for the shift',
			},
			{
				displayName: 'Can Evaluate',
				name: 'can_evaluate',
				type: 'boolean',
				default: false,
				placeholder: '',
				description: 'WhetherEmployees can create evaluations',
			},
			{
				displayName: 'Untimed',
				name: 'untimed',
				type: 'boolean',
				default: false,
				placeholder: '',
				description: 'WhetherStandby shift',
			},
			{
				displayName: 'Auto Accept',
				name: 'auto_accept',
				type: 'string',
				default: '',
				placeholder: '',
				description: 'Auto accept shift requests as long as there are open slots on the shift',
			},
			{
				displayName: 'Shift Preset_ID',
				name: 'shift_preset_id',
				type: 'number',
				default: '',
				placeholder: '',
				description: 'ID of an exisiting shift preset',
			},
			{
				displayName: 'Metadata',
				name: 'metadata',
				type: 'json',
				default: '',
				placeholder: '',
				description: 'Shift metadata as JSON',
			},
			{
				displayName: 'Break Time',
				name: 'break_time',
				type: 'number',
				default: '',
				placeholder: '',
				description: 'Break duration in minutes (Required unless untimed_break_time is present)',
			},
			{
				displayName: 'Untimed Break_time',
				name: 'untimed_break_time',
				type: 'number',
				default: '',
				placeholder: '',
				description: 'Untimed breaks in minutes (Required unless break_time is present)',
			},
			{
				displayName: 'Tag IDs[]',
				name: 'tag_ids[]',
				type: 'string',
				default: '',
				placeholder: '',
				description: 'Array of Shift Tag IDs (including from shift presets)',
			},
			{
				displayName: 'Evaluation Tag_IDs[]',
				name: 'evaluation_tag_ids[]',
				type: 'string',
				default: '',
				placeholder: '',
				description: 'Array of EvaluationTag IDs (including from shift presets)',
			},
			{
				displayName: 'Shift Breaks[][starts_at]',
				name: 'shift_breaks[][starts_at]',
				type: 'string',
				default: '',
				placeholder: '',
				description: 'Start time of the breaks',
			},
			{
				displayName: 'Shift Breaks[][ends_at]',
				name: 'shift_breaks[][ends_at]',
				type: 'string',
				default: '',
				placeholder: '',
				description: 'End time of the breaks',
			},
			{
				displayName: 'Assignment Group_IDs[]',
				name: 'assignment_group_ids[]',
				type: 'string',
				default: '',
				placeholder: '',
				description: 'Array of assignment group IDs',
			},
			{
				displayName: 'Shift Rotation_group_IDs[]',
				name: 'shift_rotation_group_ids[]',
				type: 'string',
				default: '',
				placeholder: '',
				description: 'Array of shift_rotation_group group IDs',
			},
			{
				displayName: 'Manager Note',
				name: 'manager_note',
				type: 'string',
				default: '',
				placeholder: '',
				description: 'Manager note for the Shift',
			},
			{
				displayName: 'Ignore Conflicts',
				name: 'ignore_conflicts',
				type: 'string',
				default: 'false',
				placeholder: '',
				description:
					'Whether true to ignore all conflicts listed below or an Array of specific conflicts to ignore Only warnings can be ignored, enforced conflicts will persist. Possible values are:<ul> <li>shifts_collision</li><li>absences_collision</li><li>locations_position_changed</li><li>minimum_break</li><li>maximum_working_hours</li><li>minimum_rest</li><li>maximum_earning</li><li>outside_employment_period</li><li>maximum_consecutive_working_days</li><li>restricted_shift_presets</li><li>unavailable</li><li>not_available</li></ul>.',
			},
			{
				displayName: 'qualifications[][ID]',
				name: 'qualifications[][id]',
				type: 'string',
				default: '',
				placeholder: '',
				description: 'Qualification ID',
			},
			{
				displayName: 'Qualifications Count',
				name: 'qualifications[][count]',
				type: 'string',
				default: '',
				placeholder: '',
				description: 'Required workers per qualification',
			},
		],
	},
];
