import { INodeProperties } from 'n8n-workflow';
export const getApiV1EmploymentsGetAllFields: INodeProperties[] = [
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				operation: ['getApiV1Employments'],
				resource: ['employments'],
			},
		},
		options: [
			{
				displayName: 'Company ID',
				name: 'company_id',
				type: 'number',
				default: '',
				placeholder: '',
				description: 'Filter for single Company ID',
			},
			{
				displayName: 'Page',
				name: 'page',
				type: 'number',
				default: '',
				placeholder: '',
				description: 'Pages starts with 1',
			},
			{
				displayName: 'Per Page',
				name: 'per_page',
				type: 'number',
				default: '',
				placeholder: '',
				description: 'Between 1 and 1000',
			},
			{
				displayName: 'Updated After',
				name: 'updated_after',
				type: 'string',
				default: '',
				placeholder: '',
				description: 'Return all records which are updated after',
			},
			{
				displayName: 'Created After',
				name: 'created_after',
				type: 'string',
				default: '',
				placeholder: '',
				description: 'Return all records which are created after',
			},
			{
				displayName: 'Updated Before',
				name: 'updated_before',
				type: 'string',
				default: '',
				placeholder: '',
				description: 'Return all records which are updated before',
			},
			{
				displayName: 'Created Before',
				name: 'created_before',
				type: 'string',
				default: '',
				placeholder: '',
				description: 'Return all records which are created before',
			},
			{
				displayName: 'ID',
				name: 'id',
				type: 'number',
				default: '',
				placeholder: '',
				description: 'Filter for single Employment ID',
			},
			{
				displayName: 'IDs[]',
				name: 'idsSTARTEND',
				type: 'json',
				typeOptions: {
					multipleValues: true,
					multipleValueButtonText: 'Add Tag',
				},
				default: '',
				placeholder: '',
				description: 'Filter an array of Employment ID',
			},
			{
				displayName: 'Search',
				name: 'search',
				type: 'string',
				default: '',
				placeholder: '',
				description: 'Search string to filter employees by name or staff number',
			},
			{
				displayName: 'Staff Numbers[]',
				name: 'staff_numbersSTARTEND',
				type: 'json',
				typeOptions: {
					multipleValues: true,
					multipleValueButtonText: 'Add Tag',
				},
				default: '',
				placeholder: '',
				description: 'Filter an array of Staff numbers ID',
			},
			{
				displayName: 'Company IDs[]',
				name: 'company_idsSTARTEND',
				type: 'json',
				typeOptions: {
					multipleValues: true,
					multipleValueButtonText: 'Add Tag',
				},
				default: '',
				placeholder: '',
				description: 'Filter an array of Company ID',
			},
			{
				displayName: 'Location ID',
				name: 'location_id',
				type: 'number',
				default: '',
				placeholder: '',
				description: 'Filter for Location ID',
			},
			{
				displayName: 'Locations Position_ID',
				name: 'locations_position_id',
				type: 'number',
				default: '',
				placeholder: '',
				description: 'Filter for single LocationsPosition ID',
			},
			{
				displayName: 'Locations Position_IDs[]',
				name: 'locations_position_idsSTARTEND',
				type: 'json',
				typeOptions: {
					multipleValues: true,
					multipleValueButtonText: 'Add Tag',
				},
				default: '',
				placeholder: '',
				description: 'Filter an array of LocationsPosition ID',
			},
			{
				displayName: 'Shiftplan ID',
				name: 'shiftplan_id',
				type: 'number',
				default: '',
				placeholder: '',
				description: 'Filter for single Shiftplan ID',
			},
			{
				displayName: 'Shiftplan IDs[]',
				name: 'shiftplan_idsSTARTEND',
				type: 'json',
				typeOptions: {
					multipleValues: true,
					multipleValueButtonText: 'Add Tag',
				},
				default: '',
				placeholder: '',
				description: 'Filter an array of Shiftplan ID',
			},
			{
				displayName: 'Shift Rotation_group_IDs[]',
				name: 'shift_rotation_group_idsSTARTEND',
				type: 'json',
				typeOptions: {
					multipleValues: true,
					multipleValueButtonText: 'Add Tag',
				},
				default: '',
				placeholder: '',
				description: 'Filter an array of Shift rotation group ID',
			},
			{
				displayName: 'Not In_shift_rotation_group_IDs[]',
				name: 'not_in_shift_rotation_group_idsSTARTEND',
				type: 'json',
				typeOptions: {
					multipleValues: true,
					multipleValueButtonText: 'Add Tag',
				},
				default: '',
				placeholder: '',
				description: 'Filter for employments who are not in these rotation groups',
			},
			{
				displayName: 'Is Stakeholder',
				name: 'is_stakeholder',
				type: 'boolean',
				default: false,
				placeholder: '',
				description: 'Whether Filter for Stakeholders',
			},
			{
				displayName: 'Is Owner',
				name: 'is_owner',
				type: 'boolean',
				default: false,
				placeholder: '',
				description: 'Whether Filter for Owners',
			},
			{
				displayName: 'Is Employee',
				name: 'is_employee',
				type: 'boolean',
				default: false,
				placeholder: '',
				description: 'Whether Filter for Employees',
			},
			{
				displayName: 'Invitation State',
				name: 'invitation_state',
				type: 'string',
				default: '',
				placeholder: '',
				description: 'tbd',
			},
			{
				displayName: 'Invitation States[]',
				name: 'invitation_statesSTARTEND',
				type: 'json',
				typeOptions: {
					multipleValues: true,
					multipleValueButtonText: 'Add Tag',
				},
				default: '',
				placeholder: '',
				description: 'tbd',
			},
			{
				displayName: 'Include Live_info',
				name: 'include_live_info',
				type: 'boolean',
				default: false,
				placeholder: '',
				description: 'Whether Include live info(might be slow)',
			},
			{
				displayName: 'With Deleted',
				name: 'with_deleted',
				type: 'boolean',
				default: false,
				placeholder: '',
				description: 'Whether Include soft-deleted employments',
			},
			{
				displayName: 'Qualification ID',
				name: 'qualification_id',
				type: 'number',
				default: '',
				placeholder: '',
				description: 'Filter for single Qualification ID',
			},
			{
				displayName: 'Qualification IDs[]',
				name: 'qualification_idsSTARTEND',
				type: 'json',
				typeOptions: {
					multipleValues: true,
					multipleValueButtonText: 'Add Tag',
				},
				default: '',
				placeholder: '',
				description: 'Filter an array of Qualification ID',
			},
			{
				displayName: 'Tag IDs[]',
				name: 'tag_idsSTARTEND',
				type: 'json',
				typeOptions: {
					multipleValues: true,
					multipleValueButtonText: 'Add Tag',
				},
				default: '',
				placeholder: '',
				description: 'Filter by an array of Employee Attribute IDs',
			},
			{
				displayName: 'Access Level',
				name: 'access_level',
				type: 'string',
				default: '',
				placeholder: '',
				description: 'Access level filter used for employments',
			},
			{
				displayName: 'Order Key',
				name: 'order_key',
				type: 'string',
				default: '',
				placeholder: '',
				description: 'Sort keys',
			},
			{
				displayName: 'Order Dir',
				name: 'order_dir',
				type: 'string',
				default: '',
				placeholder: '',
				description: 'Sort direction',
			},
		],
	},
];
