import { INodeProperties } from 'n8n-workflow';
export const getApiV1ShiftsGetAllFields: INodeProperties[] = [
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				operation: ['getApiV1Shifts'],
				resource: ['shifts'],
			},
		},
		options: [
			{
				displayName: 'Company ID',
				name: 'company_id',
				type: 'number',
				default: '',
				placeholder: '',
				description: 'Enter Company ID',
			},
			{
				displayName: 'Page',
				name: 'page',
				type: 'number',
				default: 1,
				placeholder: '',
				description: 'Pages starts with 1',
			},
			{
				displayName: 'Per Page',
				name: 'per_page',
				type: 'number',
				default: 1000,
				placeholder: '',
				description: 'Between 1 and 1000',
			},
			{
				displayName: 'Updated After',
				name: 'updated_after',
				type: 'string',
				default: '',
				placeholder: '',
				description: 'Return all records which are updated after',
			},
			{
				displayName: 'Created After',
				name: 'created_after',
				type: 'string',
				default: '',
				placeholder: '',
				description: 'Return all records which are created after',
			},
			{
				displayName: 'Updated Before',
				name: 'updated_before',
				type: 'string',
				default: '',
				placeholder: '',
				description: 'Return all records which are updated before',
			},
			{
				displayName: 'Created Before',
				name: 'created_before',
				type: 'string',
				default: '',
				placeholder: '',
				description: 'Return all records which are created before',
			},
			{
				displayName: 'Starts At',
				name: 'starts_at',
				type: 'string',
				default: '',
				placeholder: '',
				description: '',
			},
			{
				displayName: 'Ends At',
				name: 'ends_at',
				type: 'string',
				default: '',
				placeholder: '',
				description: '',
			},
			{
				displayName: 'ID',
				name: 'id',
				type: 'number',
				default: '',
				placeholder: '',
				description: 'Filter by Shift ID',
			},
			{
				displayName: 'IDs[]',
				name: 'ids[]',
				type: 'string',
				default: '',
				placeholder: '',
				description: 'Filter by an array of Shift IDs',
			},
			{
				displayName: 'Shiftplan ID',
				name: 'shiftplan_id',
				type: 'number',
				default: '',
				placeholder: '',
				description: 'Filter by Shiftplan ID',
			},
			{
				displayName: 'Shiftplan IDs[]',
				name: 'shiftplan_ids[]',
				type: 'string',
				default: '',
				placeholder: '',
				description: 'Filter by an array of Shiftplan IDs',
			},
			{
				displayName: 'Tag IDs[]',
				name: 'tag_ids[]',
				type: 'string',
				default: '',
				placeholder: '',
				description: 'Filter by an array of Shift Tag IDs',
			},
			{
				displayName: 'Without Tags',
				name: 'without_tags',
				type: 'boolean',
				default: false,
				placeholder: '',
				description: 'WhetherFilter shifts without Shift Tags',
			},
			{
				displayName: 'Assignment Group_IDs[]',
				name: 'assignment_group_ids[]',
				type: 'string',
				default: '',
				placeholder: '',
				description: 'Filter by an array of Assignment Groups IDs',
			},
			{
				displayName: 'Locations Position_ID',
				name: 'locations_position_id',
				type: 'number',
				default: '',
				placeholder: '',
				description: 'Filter by LocationsPosition ID',
			},
			{
				displayName: 'Locations Position_IDs[]',
				name: 'locations_position_ids[]',
				type: 'string',
				default: '',
				placeholder: '',
				description: 'Filter by an array of LocationsPosition IDs',
			},
			{
				displayName: 'Employment ID',
				name: 'employment_id',
				type: 'number',
				default: '',
				placeholder: '',
				description: 'Filter by Employment ID Cannot be used with employment_ids',
			},
			{
				displayName: 'Employment IDs[]',
				name: 'employment_ids[]',
				type: 'string',
				default: '',
				placeholder: '',
				description: 'Filter by an array of Employment IDs Cannot be used with employment_iPd',
			},
			{
				displayName: 'Only Open',
				name: 'only_open',
				type: 'boolean',
				default: false,
				placeholder: '',
				description: 'WhetherInclude only open shifts',
			},
			{
				displayName: 'Without Conflicts',
				name: 'without_conflicts',
				type: 'boolean',
				default: false,
				placeholder: '',
				description:
					'WhetherInclude only shifts without conflicts, only_open must be true and current user must be an employee only',
			},
			{
				displayName: 'Extended Info',
				name: 'extended_info',
				type: 'boolean',
				default: false,
				placeholder: '',
				description:
					'WhetherInclude fields "can_manage", "staff_shifts_count", "staff_shifts_needs_evaluation_count" in the response',
			},
			{
				displayName: 'Order Key',
				name: 'order_key',
				type: 'string',
				default: '',
				placeholder: '',
				description: 'Sort by key',
			},
			{
				displayName: 'Order Dir',
				name: 'order_dir',
				type: 'string',
				default: '',
				placeholder: '',
				description: 'Sort direction',
			},
			{
				displayName: 'Shift Preset_IDs[]',
				name: 'shift_preset_ids[]',
				type: 'string',
				default: '',
				placeholder: '',
				description:
					'Filter by an array of shift presets Use 0 or -1 for shifts with custom presets',
			},
			{
				displayName: 'Without Shift_presets',
				name: 'without_shift_presets',
				type: 'boolean',
				default: false,
				placeholder: '',
				description: 'WhetherInclude shifts with custom presets, can be used with shift_preset_ids',
			},
			{
				displayName: 'Shift Rotation_group_IDs[]',
				name: 'shift_rotation_group_ids[]',
				type: 'string',
				default: '',
				placeholder: '',
				description: 'Filter by shift rotation group IDs',
			},
			{
				displayName: 'Not In_shift_rotation_group_IDs[]',
				name: 'not_in_shift_rotation_group_ids[]',
				type: 'string',
				default: '',
				placeholder: '',
				description: 'Filter shifts that do not belong to shift rotation groups',
			},
			{
				displayName: 'Connected Group_ID',
				name: 'connected_group_id',
				type: 'number',
				default: '',
				placeholder: '',
				description: 'Filter by connected group ID',
			},
		],
	},
];
