import { INodeProperties } from 'n8n-workflow';
export const getApiV1StaffShiftsGetAllFields: INodeProperties[] = [
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				operation: ['getApiV1StaffShifts'],
				resource: ['staff_shifts'],
			},
		},
		options: [
			{
				displayName: 'Page',
				name: 'page',
				type: 'number',
				default: '',
				placeholder: '',
				description: 'Enter Pages starts with 1',
			},
			{
				displayName: 'Per Page',
				name: 'per_page',
				type: 'number',
				default: '',
				placeholder: '',
				description: 'Enter Between 1 and 1000',
			},
			{
				displayName: 'Updated After',
				name: 'updated_after',
				type: 'string',
				default: '',
				placeholder: '',
				description: 'Enter Return all records which are updated after',
			},
			{
				displayName: 'Created After',
				name: 'created_after',
				type: 'string',
				default: '',
				placeholder: '',
				description: 'Enter Return all records which are created after',
			},
			{
				displayName: 'Updated Before',
				name: 'updated_before',
				type: 'string',
				default: '',
				placeholder: '',
				description: 'Enter Return all records which are updated before',
			},
			{
				displayName: 'Created Before',
				name: 'created_before',
				type: 'string',
				default: '',
				placeholder: '',
				description: 'Enter Return all records which are created before',
			},
			{
				displayName: 'Starts At',
				name: 'starts_at',
				type: 'string',
				default: '',
				placeholder: '',
				description: 'Enter Start',
			},
			{
				displayName: 'Ends At',
				name: 'ends_at',
				type: 'string',
				default: '',
				placeholder: '',
				description: 'Enter End',
			},
			{
				displayName: 'State',
				name: 'state',
				type: 'string',
				default: '',
				placeholder: '',
				description: 'Enter State',
			},
			{
				displayName: 'ID',
				name: 'id',
				type: 'number',
				default: '',
				placeholder: '',
				description: 'Enter Filter for single StaffShift ID',
			},
			{
				displayName: 'Shift ID',
				name: 'shift_id',
				type: 'number',
				default: '',
				placeholder: '',
				description: 'Enter Filter for single Shift ID',
			},
			{
				displayName: 'Shiftplan ID',
				name: 'shiftplan_id',
				type: 'number',
				default: '',
				placeholder: '',
				description: 'Enter Filter for single Shiftplan ID',
			},
			{
				displayName: 'Employment ID',
				name: 'employment_id',
				type: 'number',
				default: '',
				placeholder: '',
				description: 'Enter Filter for single Employment ID',
			},
			{
				displayName: 'Company ID',
				name: 'company_id',
				type: 'number',
				default: '',
				placeholder: '',
				description: 'Enter Filter for single Company ID',
			},
			{
				displayName: 'IDs[]',
				name: 'idsSTARTEND',
				type: 'json',
				typeOptions: {
					multipleValues: true,
					multipleValueButtonText: 'Add Tag',
				},
				default: '',
				placeholder: '',
				description: 'Enter Filter an array of StaffShift ID',
			},
			{
				displayName: 'Shift IDs[]',
				name: 'shift_idsSTARTEND',
				type: 'json',
				typeOptions: {
					multipleValues: true,
					multipleValueButtonText: 'Add Tag',
				},
				default: '',
				placeholder: '',
				description: 'Enter Filter an array of Shift ID',
			},
			{
				displayName: 'Shiftplan IDs[]',
				name: 'shiftplan_idsSTARTEND',
				type: 'json',
				typeOptions: {
					multipleValues: true,
					multipleValueButtonText: 'Add Tag',
				},
				default: '',
				placeholder: '',
				description: 'Enter Filter an array of Shiftplan ID',
			},
			{
				displayName: 'Employment IDs[]',
				name: 'employment_idsSTARTEND',
				type: 'json',
				typeOptions: {
					multipleValues: true,
					multipleValueButtonText: 'Add Tag',
				},
				default: '',
				placeholder: '',
				description: 'Enter Filter an array of Employment ID',
			},
			{
				displayName: 'Only Open',
				name: 'only_open',
				type: 'boolean',
				default: false,
				placeholder: '',
				description: 'Whether Filter for open shifts - employment_ID needs to be present',
			},
		],
	},
];
